--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-30-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLASSSELETE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CLASSSELETE" 
   (	"CNO" NUMBER(6,0), 
	"CLNAME" VARCHAR2(50 BYTE), 
	"CLFTIME" DATE, 
	"CLETIME" DATE, 
	"CLDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.CLASSSELETE
SET DEFINE OFF;
Insert into SCOTT.CLASSSELETE (CNO,CLNAME,CLFTIME,CLETIME,CLDATE) values (111111,'capstone design',to_date('19/07/01','RR/MM/DD'),to_date('19/07/01','RR/MM/DD'),to_date('19/08/06','RR/MM/DD'));
Insert into SCOTT.CLASSSELETE (CNO,CLNAME,CLFTIME,CLETIME,CLDATE) values (222222,'Java programming',to_date('19/07/01','RR/MM/DD'),to_date('19/07/01','RR/MM/DD'),to_date('19/08/07','RR/MM/DD'));
Insert into SCOTT.CLASSSELETE (CNO,CLNAME,CLFTIME,CLETIME,CLDATE) values (333333,'HTML',to_date('19/07/01','RR/MM/DD'),to_date('19/07/01','RR/MM/DD'),to_date('19/08/08','RR/MM/DD'));
Insert into SCOTT.CLASSSELETE (CNO,CLNAME,CLFTIME,CLETIME,CLDATE) values (444444,'Database',to_date('19/07/01','RR/MM/DD'),to_date('19/07/01','RR/MM/DD'),to_date('19/08/09','RR/MM/DD'));
Insert into SCOTT.CLASSSELETE (CNO,CLNAME,CLFTIME,CLETIME,CLDATE) values (555555,'JAVA Script',to_date('19/07/01','RR/MM/DD'),to_date('19/07/01','RR/MM/DD'),to_date('19/08/10','RR/MM/DD'));
Insert into SCOTT.CLASSSELETE (CNO,CLNAME,CLFTIME,CLETIME,CLDATE) values (666666,'CSS',to_date('19/07/01','RR/MM/DD'),to_date('19/07/01','RR/MM/DD'),to_date('19/08/11','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C0011133
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011133" ON "SCOTT"."CLASSSELETE" ("CNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLASSSELETE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CLASSSELETE" ADD PRIMARY KEY ("CNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
