--------------------------------------------------------
--  파일이 생성됨 - 금요일-7월-19-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLANLIST
--------------------------------------------------------

  CREATE TABLE "SCOTT"."PLANLIST" 
   (	"CREDATE" DATE, 
	"CNAME" VARCHAR2(50 BYTE), 
	"CCONTENT" VARCHAR2(100 BYTE), 
	"PROFESSOR" VARCHAR2(30 BYTE), 
	"CROOM" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.PLANLIST
SET DEFINE OFF;
Insert into SCOTT.PLANLIST (CREDATE,CNAME,CCONTENT,PROFESSOR,CROOM) values (to_date('19/07/12','RR/MM/DD'),'capstone design','ccontent1','HONG','8403');
Insert into SCOTT.PLANLIST (CREDATE,CNAME,CCONTENT,PROFESSOR,CROOM) values (to_date('19/07/13','RR/MM/DD'),'java script','ccontent2','KIM','8407');
Insert into SCOTT.PLANLIST (CREDATE,CNAME,CCONTENT,PROFESSOR,CROOM) values (to_date('19/07/14','RR/MM/DD'),'html','ccontent3','LEE','8411');
--------------------------------------------------------
--  DDL for Index SYS_C0011129
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011129" ON "SCOTT"."PLANLIST" ("PROFESSOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PLANLIST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."PLANLIST" ADD PRIMARY KEY ("PROFESSOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
