--------------------------------------------------------
--  파일이 생성됨 - 목요일-8월-08-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FREEBOARD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."FREEBOARD" 
   (	"FREEBID" NUMBER(4,0), 
	"FREEBTITLE" VARCHAR2(50 BYTE), 
	"FREEBCONTENT" VARCHAR2(1000 BYTE), 
	"FREEBWRITER" VARCHAR2(20 BYTE), 
	"FREEBVIEWCNT" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.FREEBOARD
SET DEFINE OFF;
Insert into SCOTT.FREEBOARD (FREEBID,FREEBTITLE,FREEBCONTENT,FREEBWRITER,FREEBVIEWCNT) values (424,'자유게시판','내용3','작성자3',2);
Insert into SCOTT.FREEBOARD (FREEBID,FREEBTITLE,FREEBCONTENT,FREEBWRITER,FREEBVIEWCNT) values (1243,'자유게시판','내용3','작성자3',2);
Insert into SCOTT.FREEBOARD (FREEBID,FREEBTITLE,FREEBCONTENT,FREEBWRITER,FREEBVIEWCNT) values (1243,'자유게시판','내용3','작성자3',2);
Insert into SCOTT.FREEBOARD (FREEBID,FREEBTITLE,FREEBCONTENT,FREEBWRITER,FREEBVIEWCNT) values (1243,'자유게시판','내용3','작성자3',2);
Insert into SCOTT.FREEBOARD (FREEBID,FREEBTITLE,FREEBCONTENT,FREEBWRITER,FREEBVIEWCNT) values (123,'제목','내용','작성자',3);
Insert into SCOTT.FREEBOARD (FREEBID,FREEBTITLE,FREEBCONTENT,FREEBWRITER,FREEBVIEWCNT) values (1,'제목','내용','작성자',3);
--------------------------------------------------------
--  Constraints for Table FREEBOARD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."FREEBOARD" MODIFY ("FREEBID" NOT NULL ENABLE);
